# Exported from Render on 2026-03-28T04:20:47Z
version: "1"
services:
- type: web
  name: Team_Info_App
  runtime: node
  repo: https://github.com/Thiyanesh07/Team_Info_App
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: ALLOWED_DOMAINS
    sync: false
  - key: SUPER_ADMIN_EMAIL
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: FIREBASE_PROJECT_ID
    sync: false
  - key: FIREBASE_CLIENT_EMAIL
    sync: false
  - key: FIREBASE_PRIVATE_KEY
    sync: false
  - key: GOOGLE_SHEET_ID
    sync: false
  - key: GOOGLE_AVERAGES_SHEET_ID
    sync: false
  - key: GOOGLE_CHART_URL
    sync: false
  - key: GOOGLE_SHEET_DEPARTMENTS
    sync: false
  - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
    sync: false
  - key: GOOGLE_PRIVATE_KEY
    sync: false
  - key: GOOGLE_USER_EMAIL
    sync: false
  - key: GOOGLE_USER_PASSWORD
    sync: false
  region: singapore
  buildCommand: npm run build
  startCommand: yarn start
  autoDeployTrigger: commit
  rootDir: backend
